### ISSUE TITLE
按照star排序显示最近一周/一月的内容

### ISSUE THREAD

**Issue by yuanzhi-zhu** [bojone/papers.cool#11]
当前网站仅仅支持按照star排序某天的内容。
考虑到已经支持历史内容查看，不知道有没有可能按照star排序显示最近一周/一月的内容。
也不一定需要排序一个月内所有的paper，只需要把star数目前100的paper列出来就够了。

**Comment by bojone** [comment]
实现难度倒不是很大，只要加入按日期范围来显示文章即可。不过这个需求本质是啥呢？是打算一周看一次，还是纯粹想看看一周最火的论文是哪篇？

**Comment by yuanzhi-zhu** [comment]
对于不熟悉但是还算感兴趣的领域，可能隔段时间看下大家关注的方向这样

**Comment by yuanzhi-zhu** [comment]
@bojone 有一个更简单的功能可以快速实现一下。
比如我已经好几天没看papers.cool，然后我点开一个过去日期的页面，我需要手动在网址后面加上&sort=1才能将该日期的论文按照star排序。
所以需求就是在每个每日的论文页面，添加一个按钮，用来调整排序方式。

**Comment by bojone** [comment]
> @bojone 有一个更简单的功能可以快速实现一下。 比如我已经好几天没看papers.cool，然后我点开一个过去日期的页面，我需要手动在网址后面加上&sort=1才能将该日期的论文按照star排序。 所以需求就是在每个每日的论文页面，添加一个按钮，用来调整排序方式。

我修改了一下js，目前可以这样子解决：首页有每个分类带sort=1的链接，点击进去就是最新一天的排序结果，然后页面头部有一个日期，这个日期是可以点击切换的，切换后同样保持sort=1参数。
