### ISSUE TITLE
是否可以我提供paper的arxiv链接然后调用kimi来总结呢？

### ISSUE THREAD

**Issue by zhangxjohn** [bojone/papers.cool#22]
是否可以我提供paper的arxiv链接然后调用kimi来总结呢？
虽然这偏离了该项目刷最新论文的原则，不知道大家有么有这个需求？

**Comment by WeihongPan** [comment]
+1

**Comment by youngfish42** [comment]
观察一下现在的 arxiv 文章的超链接，比如
`https://papers.cool/arxiv/2405.06639`

你可以把最后的 arxiv-id 换成自己想要分析的论文的id，比如
`https://papers.cool/arxiv/1503.02531`
