### ISSUE TITLE
【功能建议】增加论文原文链接

### ISSUE THREAD

**Issue by Zhong-Zhang** [bojone/papers.cool#28]
建议可在[PDF] [Copy] [Kimi]之后增加原文跳转链接[Link]，由此可方便使用一些浏览器插件比如Mendeley Web Importer、Tampermonkey

**Comment by Zhong-Zhang** [comment]
另外网站似乎有内存泄露问题，经历过几次网页内存占用飙升到8GB以上直到被kill，暂不清楚如何复现

**Comment by Zhong-Zhang** [comment]
注意到#数字已经实现了该功能

**Comment by bojone** [comment]
> 注意到#数字已经实现了该功能

对，这个有点隐蔽，被很多读者吐槽过，但实在没有想到其他更好的入口了，如果有更好的建议欢迎提出。

**Comment by bojone** [comment]
> 另外网站似乎有内存泄露问题，经历过几次网页内存占用飙升到8GB以上直到被kill，暂不清楚如何复现

这是进行了搜索操作还是什么操作呢？我暂时没法复现这个问题。

**Comment by Zhong-Zhang** [comment]
> > 另外网站似乎有内存泄露问题，经历过几次网页内存占用飙升到8GB以上直到被kill，暂不清楚如何复现
> 
> 这是进行了搜索操作还是什么操作呢？我暂时没法复现这个问题。

测试环境如下：
MacBook Pro 14寸 M3
macOS Sonoma 14.2
Safari Version 17.2 (19617.1.17.11.9)

在简单地上下滚动网页，同时点击kimi和pdf之后内存占用到了5G以上，不知道是否正常
<img width="951" alt="image" src="https://github.com/bojone/papers.cool/assets/42954562/f42b88e1-eb36-4c8a-bf2d-f9c2ec5ce126">

求教如何才能导出Debug日志
