### ISSUE TITLE
关于 Papers.cool 的使用

### ISSUE THREAD

**Issue by GeoffreyChen777** [bojone/papers.cool#30]
Hello 你好，我是 CV 领域的一个博士生，同时也是开源文献管理工具 [Paperlib](https://github.com/Future-Scholars/paperlib) 的 leader。多年前因为现有的文献管理工具无法很好处理 AI 领域大量会议的 metadata 而开发，自己日常科研很常用。

我日常读您的博客，收益良多，感谢！

papers.cool 刷论文很方便，所以在此想请问能否授权我将其嵌入进 Paperlib 的插件中。该插件可能会访问展示您的 papers.cool，注入修改部分网页结构（当然是本地的，不会注入您的代码），以支持导入论文到 Paperlib等。

期待您的回复。
祝好。

Changrui Chen
University of Warwick & Future Scholars

**Comment by bojone** [comment]
欢迎，我没有意见，感谢认可

**Comment by GeoffreyChen777** [comment]
谢谢！
