### ISSUE TITLE
对于PDF插件快速跳转

### ISSUE THREAD

**Issue by MedAIerHHL** [bojone/papers.cool#36]
苏神好！ 问题的起因是google对订阅作者的推送有时候链接是直接的arxiv的pdf如：https://arxiv.org/pdf/2404.05916.pdf。
这个时候就需要取中间的数字然后重新搜下，能否在插件直接跳转，或者实现对https://arxiv.org/pdf/2404.05916.pdf 链接分解arxiv号然后跳转。

**Comment by bojone** [comment]
所以你的问题是啥？是指chrome插件中如果访问的是pdf直链，则右键菜单不生效？
