### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by bjzhb666** [bojone/papers.cool#39]
![image](https://github.com/bojone/papers.cool/assets/71651717/af1d5298-9d31-495d-b533-be23c41872cc)
在使用arxiv得时候用插件，右键点击跳转cool paper后出现错误

**Comment by bojone** [comment]
这个[PDF]是你用自己的网络访问arxiv的pdf链接的，所以出现500错误意味着你当时的网络访问arxiv大概率有障碍。

**Comment by bojone** [comment]
暂时修复了，更深层次的原因还在查

**Comment by bojone** [comment]
已经fixed了
