### ISSUE TITLE
页面filter bug报告

### ISSUE THREAD

**Issue by lyyi599** [bojone/papers.cool#4]
感谢大佬工作。
发现一个在页面上的小问题，如果使用filter筛选出的结果为空，没法上拉，似乎就不好返回到筛选之前了。

**Comment by bojone** [comment]
将光标移动到bar的位置，bar同样也会出现；另外刷新页面也能恢复原状。不知道这样能否解决你的问题？

**Comment by lyyi599** [comment]
> 将光标移动到bar的位置，bar同样也会出现；另外刷新页面也能恢复原状。不知道这样能否解决你的问题？

thanks for your reply.
竟然不知道移动到bar上可以看到。之前一段时间确实是fliter之后刷新的返回全部的，只是觉得这样子不很优雅就提了一个issue。已解决，感谢大佬 : )

**Comment by bojone** [comment]
> > 将光标移动到bar的位置，bar同样也会出现；另外刷新页面也能恢复原状。不知道这样能否解决你的问题？
> 
> thanks for your reply. 竟然不知道移动到bar上可以看到。之前一段时间确实是fliter之后刷新的返回全部的，只是觉得这样子不很优雅就提了一个issue。已解决，感谢大佬 : )

没事，这是纯粹模仿很多移动端的bar设计，很多地方的bar都是移动或者悬停就显示，否则延时隐藏。
