### ISSUE TITLE
增加支持多个关键词进行搜索过滤或者高亮的功能

### ISSUE THREAD

**Issue by X1AOX1A** [bojone/papers.cool#50]
现在的页面过滤只能支持一组关键词，如高亮包含 "multimodal" 的内容。但是无法支持同时高亮多组关键词。

期望功能：支持同时高亮多组关键词，如输入 "multimodal, MLLM"，其中关键词通过 ", " 进行分割，搜索后可以高亮 / 过滤任一包含其中一个关键词的文本。

<img width="548" alt="Screenshot 2024-06-12 at 10 43 16" src="https://github.com/bojone/papers.cool/assets/52992366/2a4b3636-cbe5-4708-a3e3-2f79368fde3e">

**Comment by bojone** [comment]
可以每行一个关键词，多个关键词是“或”的关系。还是说你想实现的是“与”的关系？

**Comment by X1AOX1A** [comment]
感谢，我指的是“或”的关系，已通过换行解决，再次感谢！
