### ISSUE TITLE
拉取 Arxiv 来源的文章遇到无法打开的问题

### ISSUE THREAD

**Issue by youngfish42** [bojone/papers.cool#51]
如题，无法正确打开相应的论文界面，也无错误提示或报告。测试链接如下：

https://papers.cool/arxiv/2107.00233

https://papers.cool/arxiv/1907.01132

**Comment by bojone** [comment]
似乎遭遇了一点恶意攻击，暂时通过重启的办法解决了，我继续观察一下。

**Comment by youngfish42** [comment]
非常感谢您的及时反馈和问题修复！
