### ISSUE TITLE
苏老师你好, 在使用时我发现一个问题, 我无法使用"全站搜索"搜索到ACL的论文.

### ISSUE THREAD

**Issue by Night-Quiet** [bojone/papers.cool#53]
如这是一篇ACL2019主会论文: Generating Natural Language Adversarial Examples through Probability Weighted Word Saliency
我在ACL2019主会一直往下滑, 通过全文匹配能搜到:

![c7ab27f2fa36ed36817d66beda938e7](https://github.com/bojone/papers.cool/assets/73934131/2d803321-4976-4b52-a8cd-88ca17794428)

但是我将这个论文标题在"全站搜索"搜, 却没办法搜到:

![b826ed3f05c5e8dfde1c0fd3afc14fe](https://github.com/bojone/papers.cool/assets/73934131/756c802f-4385-47c6-a7c7-860bb1e12c53)

我查阅了README, 看一下使用方式:

![16d9553b08bee4f401abd10fa8d0de3](https://github.com/bojone/papers.cool/assets/73934131/f2b08122-280e-4b54-bc45-96b891807907)

似乎使用方式是正确的.

请问是"全站搜索"还未支持Arxiv上没有的会议论文? 还是我存在使用问题? 谢谢苏老师.

**Comment by bojone** [comment]
首页的搜索框有个向下的“>>“，点击它可以选择branch，选择venue即可。

目前不支持arxiv和venue的混合搜索（papers.cool 的固有设计导致，一时半会兼容不了，抱歉）

**Comment by Night-Quiet** [comment]
感谢回复, 搜索成功.

![71a8b7a48ead3f17ba7f4edb28e03e0](https://github.com/bojone/papers.cool/assets/73934131/ae081cd5-1040-47b4-8e13-44bee84ce441)
