### ISSUE TITLE
希望添加多级排序/字典排序功能

### ISSUE THREAD

**Issue by tgyy1995** [bojone/papers.cool#60]
比如说按收藏排序后，对于那些0收藏的论文再按照偏好排序

感谢苏神提供这么好的平台

**Comment by bojone** [comment]
考虑过，没想到比较好的入口设计方式。另外就是偏好和星标分数其实都近乎是一个连续值，连续值多重排序总感觉有点奇怪（生效的情况可能比较小）

**Comment by tgyy1995** [comment]
对于星标排序，我认为可以自动对相同星标数的论文使用偏好排序（目前好像是随机的？）而不用添加新的入口（或者至少对0星标的论文进行偏好排序，通常0星标的论文很多而又不想都看）。对于偏好排序，确实多重排序的价值不大。
