### ISSUE TITLE
有可能增加所搜索内容的 rss 链接吗

### ISSUE THREAD

**Issue by Muyun99** [bojone/papers.cool#61]
例如最近很关注具身里的 grasp 任务，通过 cool paper 搜索 grasp topic 并按照时间排序是 

https://papers.cool/arxiv/search?highlight=1&query=grasp&sort=0

需求：希望对 query 的页面也增加 feed，这个需求是否在计划中呢～

**Comment by Muyun99** [comment]
感谢苏神提供这么好的平台，结合 RSS 使用真的非常棒！

**Comment by bojone** [comment]
安排上（最难的不是设计功能，而是设计入口～

**Comment by bojone** [comment]
列表页顶部现在增加了一个RSS按钮，点击可以打开当前页面对应的RSS链接（搜索页面也生效），欢迎测试

**Comment by Muyun99** [comment]
收到，感谢剑林老师，用下来暂时没有发现问题～
