### ISSUE TITLE
想问下调用 arxiv api 接口时传入的参数是什么？我自己部署的时候不论用 submitted date 还是 updated date 做排序都无法拿到最新的结果

### ISSUE THREAD

**Issue by zxxmxd** [bojone/papers.cool#62]
比如我在 2024-10-14 进行查询，返回获得的结果第一条为 2024-10-10T17:59:59Z 的文章。
base_url = "http://export.arxiv.org/api/query?"
query = "cat:cs.AI"
params = {
    "search_query": query,
    "start": 0,           # Starting index (useful for pagination)
    "max_results": 1,  # Number of results to fetch
    "sortBy": "submittedDate",
    "sortOrder": "descending"
}

**Comment by bojone** [comment]
为了保证阅读效果跟arxiv官网一致，列表页是直接爬官网列表页的，如 https://arxiv.org/list/cs.CL/recent
