### ISSUE TITLE
[Feature] 增加收起按钮

### ISSUE THREAD

**Issue by timelic** [bojone/papers.cool#66]
<img width="1255" alt="截屏2024-10-31 09 42 50" src="https://github.com/user-attachments/assets/d2e31f30-567e-4ced-a238-6cae7de6a42d">

希望能在每一个block的下方，或者右下角增加一个“收起”按钮。刷论文时候点击该按钮可以快速收起，不打断论文阅读流。现在只能滚动回上面点击收起，比较难受。

**Comment by bojone** [comment]
你的意思是点击一个缩回按钮，就把[PDF]和[Kimi]的结果隐藏吗？

**Comment by timelic** [comment]
> 你的意思是点击一个缩回按钮，就把[PDF]和[Kimi]的结果隐藏吗？

是的，该block变成和没打开PDF和KIWI的样子🥹

**Comment by bojone** [comment]
> > 你的意思是点击一个缩回按钮，就把[PDF]和[Kimi]的结果隐藏吗？
> 
> 是的，该block变成和没打开PDF和KIWI的样子🥹

简单在每篇论文下方加了个折叠按钮（点击Kimi或PDF时才显示），欢迎测试

**Comment by timelic** [comment]
我看到了，和我想象中一样，非常感谢🙏
