### ISSUE TITLE
希望可以增加过去日期的xml/json数据列表

### ISSUE THREAD

**Issue by BladeMonster** [bojone/papers.cool#69]
当前feed可以导出xml，但是只有当前日期的，希望可以增加过去日期的xml/json数据列表导出功能，用于个人数据分析整理，万分感谢！！！

**Comment by bojone** [comment]
feed的初衷本身是lastest，历史数据的feed没太明白意义。如果要爬数据的话，其实直接爬html页面加PyQuery解析也很简单的。

**Comment by BladeMonster** [comment]
好的好的，我也后知后觉意识到，谢谢苏神回复
