### ISSUE TITLE
手机端与电脑端同步

### ISSUE THREAD

**Issue by Winn1y** [bojone/papers.cool#7]
有无考虑手机看到比较好的文章，可以一键打包pdf到桌面pc，或者邮箱也可以，因为一般情况下可能在路上喜欢手机刷一下paper，遇到比较感兴趣的paper但是在路上手机不太好认真看，想到实验室电脑看，这时候需要一个个从手机check发过去，就有点慢，如果可以把当天看到比较感兴趣的paper一键发到pc（类似取件码）或者发到邮箱一键下载，就很方便了！

很好的项目，支持一下~

**Comment by bojone** [comment]
好想法，这个可以支持！

**Comment by bojone** [comment]
目前暂时以如下方式支持：
- 点击列表页下方的Bar中间的星星，就会出现点击过[PDF]或者[Kimi]的论文列表；
- 目前这里多了一个“Export”按钮；
- 点击“Export”后将打开一个新页面，新页面只包含点击过的论文；
- 复制这个新页面的链接，到其他设备打开即可。

**Comment by Winn1y** [comment]
能否选择哪些papers可以导出？因为可能存在误点或者觉得质量一般的paper @bojone  目前体验很好，太棒了。

**Comment by bojone** [comment]
> 能否选择哪些papers可以导出？因为可能存在误点或者觉得质量一般的paper @bojone 目前体验很好，太棒了。

很快就有了～

**Comment by bojone** [comment]
> 能否选择哪些papers可以导出？因为可能存在误点或者觉得质量一般的paper @bojone 目前体验很好，太棒了。

已完成。现在每个title右边多了个星星，可以去除/恢复星标，去除星标的不会被Export。

**Comment by Winn1y** [comment]
@bojone  太棒的体验了，点赞，试用了十天，还发现了一个问题有关于arxiv的加载，国内速度普遍较慢，一般有时候需要等待几秒到几分钟不等，虽然靠翻墙能解决，但有时候在手机体验的时候就没专门去翻墙，有时候在刷的时候点了pdf在等，然后就往后刷了，刷到最后发现前面的一些pdf总是忘了看。这类用户习惯可以考究一下怎么缓解，当然非必要哈，因为目前翻墙还是能稍微缓解这种用户习惯的问题。

**Comment by Winn1y** [comment]
另外，建议把arxiv的comment补上，有时候在补充信息里面会说明被哪些会议录取了，这个信息有时候也挺关键的。

**Comment by bojone** [comment]
> @bojone 太棒的体验了，点赞，试用了十天，还发现了一个问题有关于arxiv的加载，国内速度普遍较慢，一般有时候需要等待几秒到几分钟不等，虽然靠翻墙能解决，但有时候在手机体验的时候就没专门去翻墙，有时候在刷的时候点了pdf在等，然后就往后刷了，刷到最后发现前面的一些pdf总是忘了看。这类用户习惯可以考究一下怎么缓解，当然非必要哈，因为目前翻墙还是能稍微缓解这种用户习惯的问题。

点击Bar的阅读记录窗口的标题，可以回到那篇论文的位置，我都是这样翻看一下自己点击过哪些paper，有没有漏。因为即便[PDF]不用等，有时候[Kimi]也是要等的（你是第一个点击[Kimi]的情况下），所以这个没法完全避免。

> 
另外，建议把arxiv的comment补上，有时候在补充信息里面会说明被哪些会议录取了，这个信息有时候也挺关键的。

我看看实现方便不

**Comment by bojone** [comment]
> 另外，建议把arxiv的comment补上，有时候在补充信息里面会说明被哪些会议录取了，这个信息有时候也挺关键的。

我想了一下，实现是方便的，但还是决定不加入了。

comment的内容大致上有两类，一类是标记当前版本的删改情况，另一类就是标记被什么会议接受之类的荣誉。前者对筛选论文没有帮助，后者容易造成偏见（顶会的一定是好工作？）。我个人不建议从是否中稿、作者、作者单位等容易带有偏见的信息来筛选论文，更希望大家能够关注论文本质的质量，给每一篇论文一个公平的机会。

**Comment by Winn1y** [comment]
Comment这块有些争议，因为有些时候有些paper只是拿出来占坑，后续还会修改，但一般会议已录用的paper基本确定不会有较大改动，以及说投稿到哪，可以相对的借鉴投稿方向，并检索相关会议的其他相似论文；不过偏见这点确实有需考量，这块确实得想想，感谢你为科研社区的努力。

**Comment by sc-hua** [comment]
Comment 这部分可否加个 checkbox 来设置，可以默认关闭。

因为有的时候想看最近有哪些工作中稿比较方便一些。
